# Generated by Django 3.0.7 on 2020-10-15 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='topic',
        ),
    ]
