# Generated by Django 3.0.7 on 2020-10-15 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0003_auto_20201015_1409'),
        ('posts', '0007_remove_post_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='topic',
            field=models.ForeignKey(default='default', on_delete=django.db.models.deletion.CASCADE, to='topic.Topic'),
        ),
    ]
