# Generated by Django 3.0.7 on 2020-10-15 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0002_auto_20201014_1902'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['url_name']},
        ),
    ]
